/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectovivienda2.igu;

import com.mycompany.proyectovivienda2.logica.Controlador;
import com.mycompany.proyectovivienda2.logica.Venta;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago
 */
public class ModificarVenta extends javax.swing.JFrame {
    
    Controlador control = null;
    int id;
    Venta ven;

    /**
     * Creates new form Ventas
     */
    public ModificarVenta(int id) {
        control = new Controlador();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistroVenta = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblIntereses = new javax.swing.JLabel();
        lblCuotas = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        lblFechaEscritura = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        txtPrecioTotal = new javax.swing.JTextField();
        txtCuotas = new javax.swing.JTextField();
        txtIntereses = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtFechaEscritura = new javax.swing.JTextField();
        txtVendedor = new javax.swing.JTextField();
        btnLimpiarVenta = new javax.swing.JButton();
        btnRegistrarVenta = new javax.swing.JButton();
        lblObrasVanguard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblRegistroVenta.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblRegistroVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistroVenta.setText("MODIFICAR VENTA");

        lblMatricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lblMatricula.setText("MATRICULA:");

        lblIntereses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntereses.setForeground(new java.awt.Color(255, 255, 255));
        lblIntereses.setText("INTERESES:");

        lblCuotas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCuotas.setForeground(new java.awt.Color(255, 255, 255));
        lblCuotas.setText("CUOTAS:");

        lblVendedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVendedor.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor.setText("VENDEDOR:");

        lblFechaEscritura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFechaEscritura.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaEscritura.setText("FECHA DE ESCRITURA:");

        lblPrecioTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioTotal.setText("PRECIO TOTAL:");

        btnLimpiarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiarVenta.setText("LIMPIAR");
        btnLimpiarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarVentaActionPerformed(evt);
            }
        });

        btnRegistrarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarVenta.setText("REGISTRAR");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        lblObrasVanguard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObrasVanguard.setForeground(new java.awt.Color(255, 255, 255));
        lblObrasVanguard.setText("Obras Vanguard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIntereses)
                    .addComponent(lblCuotas)
                    .addComponent(lblPrecioTotal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtCuotas)
                    .addComponent(txtIntereses))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnLimpiarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMatricula)
                                    .addComponent(lblFechaEscritura))
                                .addContainerGap(275, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(txtVendedor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaEscritura, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVendedor, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblObrasVanguard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistroVenta)
                .addGap(234, 234, 234))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblRegistroVenta)
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula)
                    .addComponent(lblPrecioTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMatricula)
                    .addComponent(txtPrecioTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuotas)
                    .addComponent(lblVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVendedor)
                    .addComponent(txtCuotas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntereses)
                    .addComponent(lblFechaEscritura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(lblObrasVanguard)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarVentaActionPerformed
        txtPrecioTotal.setText("");
        txtCuotas.setText("");
        txtIntereses.setText("");
        txtMatricula.setText("");
        txtVendedor.setText("");
        txtFechaEscritura.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarVentaActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        
        String precioTotal = txtPrecioTotal.getText();  // Deja precioTotal como String
        String cuotasTexto = txtCuotas.getText();       // El campo cuotas es int
        String interesesTexto = txtIntereses.getText(); // El campo intereses es double
        String matricula = txtMatricula.getText();      // Campo matricula como String
        String vendedor = txtVendedor.getText();        // Campo vendedor como String
        String fechaEscrituraTexto = txtFechaEscritura.getText();  // Campo fechaEscritura como String

        // Validar si los campos no están vacíos
        

        try {
            // Convertir cuotas y intereses a sus tipos correspondientes
            int cuotas = Integer.parseInt(cuotasTexto);                // Convertir cuotas a int
            double intereses = Double.parseDouble(interesesTexto);     // Convertir intereses a double

            // Convertir la fechaEscritura de texto a un objeto Date
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");  // Asumimos formato 'yyyy-MM-dd'
            java.util.Date fechaEscritura = sdf.parse(fechaEscrituraTexto);  // Convertir el texto a fecha

            // Llamar al método registrarVenta con los parámetros convertidos
            control.registrarVenta(precioTotal, cuotas, intereses, matricula, vendedor, fechaEscritura);

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Venta registrada exitosamente.");

            // Limpiar los campos de texto
            txtPrecioTotal.setText("");
            txtCuotas.setText("");
            txtIntereses.setText("");
            txtMatricula.setText("");
            txtVendedor.setText("");
            txtFechaEscritura.setText("");

        } catch (NumberFormatException e) {
            // Manejar errores de conversión de números (cuotas o intereses)
            JOptionPane.showMessageDialog(this, "Error: Asegúrese de que los campos 'Cuotas' e 'Intereses' contienen valores numéricos válidos.");
        } catch (java.text.ParseException e) {
            // Manejar errores de formato de fecha
            JOptionPane.showMessageDialog(this, "Error: La fecha de escritura debe tener el formato 'yyyy-MM-dd'.");
        } catch (IllegalArgumentException e) {
            // Manejar cualquier otro error que pueda ocurrir
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    public void mostrarMensaje(String mensaje, String tipo, String titulo){
        JOptionPane optionPane = new JOptionPane(mensaje);
        if(tipo.equals("Info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }
        else if (tipo.equals("Error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog  = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarVenta;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuotas;
    private javax.swing.JLabel lblFechaEscritura;
    private javax.swing.JLabel lblIntereses;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblObrasVanguard;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblRegistroVenta;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JTextField txtCuotas;
    private javax.swing.JTextField txtFechaEscritura;
    private javax.swing.JTextField txtIntereses;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtPrecioTotal;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables

}
