/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectovivienda2.igu;

import com.mycompany.proyectovivienda2.logica.Controlador;
import com.mycompany.proyectovivienda2.logica.Torre;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago
 */
public class ModificarTorre extends javax.swing.JFrame {
    
    Controlador control = null;
    int id;
    Torre tor;

    /**
     * Creates new form Torres
     */
    public ModificarTorre(int id) {
        control = new Controlador();
        initComponents();
        setLocationRelativeTo(null);
        cargarDatos(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistroTorres = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNumeroPisos = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumeroPisos = new javax.swing.JTextField();
        btnliMPIAR = new javax.swing.JButton();
        btnRegistrarTorre = new javax.swing.JButton();
        btnRegistrarInmueble = new javax.swing.JButton();
        btnMenuAdmin = new javax.swing.JButton();
        lblObrasVanguard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblRegistroTorres.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblRegistroTorres.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistroTorres.setText("MODIFICAR  TORRE");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("NOMBRE:");

        lblNumeroPisos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumeroPisos.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroPisos.setText("NUMERO DE PISOS:");

        btnliMPIAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnliMPIAR.setText("LIMPIAR");
        btnliMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliMPIARActionPerformed(evt);
            }
        });

        btnRegistrarTorre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarTorre.setText("REGISTRAR");
        btnRegistrarTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTorreActionPerformed(evt);
            }
        });

        btnRegistrarInmueble.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarInmueble.setText("REGISTRAR INMUEBLE");
        btnRegistrarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarInmuebleActionPerformed(evt);
            }
        });

        btnMenuAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuAdmin.setText("MENU");
        btnMenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAdminActionPerformed(evt);
            }
        });

        lblObrasVanguard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObrasVanguard.setForeground(new java.awt.Color(255, 255, 255));
        lblObrasVanguard.setText("Obras Vanguard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumeroPisos)
                            .addComponent(lblNombre)
                            .addComponent(txtNumeroPisos, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(txtNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnRegistrarTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegistrarInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnliMPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblObrasVanguard)
                .addContainerGap(790, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistroTorres)
                .addGap(229, 229, 229))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblRegistroTorres)
                .addGap(162, 162, 162)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroPisos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnliMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(lblObrasVanguard)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnliMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliMPIARActionPerformed
        txtNombre.setText("");
        txtNumeroPisos.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnliMPIARActionPerformed

    private void btnRegistrarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarInmuebleActionPerformed
        Inmuebles irInmueble = new Inmuebles();
        irInmueble.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarInmuebleActionPerformed

    private void btnMenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAdminActionPerformed
        PanelAdministrador irMenu= new PanelAdministrador();
        irMenu.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuAdminActionPerformed

    private void btnRegistrarTorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTorreActionPerformed
        
        String nombre = txtNombre.getText();
        String numeroPisosTexto = txtNumeroPisos.getText();

        
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la torre no puede estar vacio.");
            return;
        }

        if (numeroPisosTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El numero de pisos no puede estar vacio.");
            return;
        }

        try {
            
            int numeroPisos = Integer.parseInt(numeroPisosTexto);

            
            control.registrarTorre(nombre, numeroPisos);
            JOptionPane.showMessageDialog(this, "Torre registrada exitosamente.");
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "El numero de pisos debe ser un numero valido.");
        } catch (IllegalStateException e) {
            
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

        txtNombre.setText("");
        txtNumeroPisos.setText("");
        
        control.modificarTorre(tor,nombre,numeroPisosTexto);
        
        mostrarMensaje("Se modifico correctamente","Info","Modificacion correcta");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarTorreActionPerformed
    public void mostrarMensaje(String mensaje, String tipo, String titulo){
        JOptionPane optionPane = new JOptionPane(mensaje);
        if(tipo.equals("Info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }
        else if (tipo.equals("Error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog  = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuAdmin;
    private javax.swing.JButton btnRegistrarInmueble;
    private javax.swing.JButton btnRegistrarTorre;
    private javax.swing.JButton btnliMPIAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroPisos;
    private javax.swing.JLabel lblObrasVanguard;
    private javax.swing.JLabel lblRegistroTorres;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroPisos;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos(int id) {
        this.tor = control.traerTorre(id);
        
        txtNombre.setText(tor.getNombre());
        txtNumeroPisos.setText(String.valueOf(tor.getNumPisos()));
    }
}
