/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectovivienda2.igu;

import com.mycompany.proyectovivienda2.logica.Controlador;
import com.mycompany.proyectovivienda2.logica.Inmueble;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santiago
 */
public class VerDatosInmueble extends javax.swing.JFrame {

    Controlador control = null;
    /**
     * Creates new form VerDatosInmueble
     */
    public VerDatosInmueble() {
        control = new Controlador();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDatosInmuebles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInmuebles = new javax.swing.JTable();
        btnModificarInmueble = new javax.swing.JButton();
        btnEliminarInmueble = new javax.swing.JButton();
        btnMenuAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblDatosInmuebles.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblDatosInmuebles.setForeground(new java.awt.Color(255, 255, 255));
        lblDatosInmuebles.setText("DATOS INMUEBLE");

        TablaInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaInmuebles);

        btnModificarInmueble.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificarInmueble.setText("MODIFICAR");
        btnModificarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarInmuebleActionPerformed(evt);
            }
        });

        btnEliminarInmueble.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarInmueble.setText("ELIMINAR");
        btnEliminarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInmuebleActionPerformed(evt);
            }
        });

        btnMenuAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuAdministrador.setText("MENU");
        btnMenuAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnModificarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btnEliminarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenuAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDatosInmuebles)
                .addGap(232, 232, 232))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblDatosInmuebles)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnMenuAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAdministradorActionPerformed
        PanelAdministrador irAdmin = new PanelAdministrador();
        irAdmin.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuAdministradorActionPerformed

    private void btnEliminarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInmuebleActionPerformed
        
        if(TablaInmuebles.getRowCount()>0){
            if(TablaInmuebles.getSelectedRow()!=-1){
                int id = Integer.parseInt(String.valueOf(TablaInmuebles.getValueAt(TablaInmuebles.getSelectedRow(),0)));
                control.eliminarInmueble(id);   
                
                mostrarMensaje("Inmueble eliminado correctamente","Info","Se elimino");
                cargarTabla();
            }
            else {
                mostrarMensaje("No selecciono ningun Inmueble","Error","Error al eliminar");
            }
        }
        else {
            mostrarMensaje("No hay nada para eliminar en la tabla","Error","Error al eliminar");
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarInmuebleActionPerformed

    private void btnModificarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarInmuebleActionPerformed
        if(TablaInmuebles.getRowCount()>0){
            if(TablaInmuebles.getSelectedRow()!=-1){
                int id = Integer.parseInt(String.valueOf(TablaInmuebles.getValueAt(TablaInmuebles.getSelectedRow(),0)));
                ModificarInmueble modi = new ModificarInmueble(id);
                modi.setVisible(true);
                modi.setLocationRelativeTo(null);
                dispose();
                
                
            }
            else {
                mostrarMensaje("No selecciono ningun Inmueble","Error","Error al eliminar");
            }
        }
        else {
            mostrarMensaje("No hay nada para eliminar en la tabla","Error","Error al eliminar");
}
    }//GEN-LAST:event_btnModificarInmuebleActionPerformed
    public void mostrarMensaje(String mensaje, String tipo, String titulo){
        JOptionPane optionPane = new JOptionPane(mensaje);
        if(tipo.equals("Info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }
        else if (tipo.equals("Error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog  = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerDatosInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerDatosInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInmuebles;
    private javax.swing.JButton btnEliminarInmueble;
    private javax.swing.JButton btnMenuAdministrador;
    private javax.swing.JButton btnModificarInmueble;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatosInmuebles;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        DefaultTableModel modeloTabla = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        //nombre de las columnas para la tabal inmuebles
        String titulos[] = {"ID","Valor","TipoUnidad","Area"};
        modeloTabla.setColumnIdentifiers(titulos);
        
        //carga de los datos desde la base de datos 
        List <Inmueble> listaInmuebles = control.traerInmuebles();
        
        if(listaInmuebles!=null){
            for(Inmueble inm: listaInmuebles){
                Object[] objeto = {inm.getId(),inm.getTipoUnidad(), inm.getValor(), inm.getArea()};
                modeloTabla.addRow(objeto);
            }
        }
        
        TablaInmuebles.setModel(modeloTabla);
    }
    
    
}
